name: CI - build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2

      - name: run Build
        run: |
          pnpm install
          pnpm run build
