name: CI - lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Lint

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.2

      - name: run Lint
        run: |
          pnpm install
          pnpm run lint
