name: CI - test

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2

      - name: run Test
        run: |
          pnpm install
          pnpm run test
